// Mocks generated by Mockito 5.4.6 from annotations
// in makerslab_app/test/core/data/repositories/theme_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:makerslab_app/core/data/datasources/theme_local_datasource.dart'
    as _i2;
import 'package:makerslab_app/core/domain/entities/theme_preference.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ThemeLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockThemeLocalDataSource extends _i1.Mock
    implements _i2.ThemeLocalDataSource {
  MockThemeLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ThemePreference> getThemePreference() =>
      (super.noSuchMethod(
            Invocation.method(#getThemePreference, []),
            returnValue: _i3.Future<_i4.ThemePreference>.value(
              _i4.ThemePreference.system,
            ),
          )
          as _i3.Future<_i4.ThemePreference>);

  @override
  _i3.Future<void> saveThemePreference(_i4.ThemePreference? preference) =>
      (super.noSuchMethod(
            Invocation.method(#saveThemePreference, [preference]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
